import { useEffect, useState } from 'react'
import type { ProjectCache, ProjectCardData } from './projects'

type UseProjectsResult = {
  projects: ProjectCardData[]
  isLoading: boolean
  error: string | null
}

/**
 * Loads the static project cache generated by scripts/generate-project-cache.mjs.
 * Shared by the home page (featured cards) and the projects page (full index).
 */
export function useProjects(): UseProjectsResult {
  const [projects, setProjects] = useState<ProjectCardData[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let isCancelled = false

    async function loadProjects() {
      setIsLoading(true)
      setError(null)
      try {
        const response = await fetch(`${import.meta.env.BASE_URL}data/projects-cache.json`, {
          cache: 'no-cache',
        })

        if (!response.ok) {
          throw new Error('Project cache request failed')
        }

        const payload = (await response.json()) as ProjectCache

        if (isCancelled) {
          return
        }

        const sortedProjects = [...payload.projects].sort((left, right) => {
          if (left.sortOrder !== right.sortOrder) {
            return left.sortOrder - right.sortOrder
          }

          return left.title.localeCompare(right.title)
        })

        setProjects(sortedProjects)

        // 'stale' entries kept their previous good details, so there is nothing to tell visitors.
        if (sortedProjects.some((project) => project.sourceStatus === 'error')) {
          setError('Some project details could not be loaded.')
        }
      } catch {
        if (isCancelled) {
          return
        }

        setError('Project data is temporarily unavailable.')
      } finally {
        if (!isCancelled) {
          setIsLoading(false)
        }
      }
    }

    void loadProjects()

    return () => {
      isCancelled = true
    }
  }, [])

  return { projects, isLoading, error }
}
